export const PATH = {
    HOME: '/',
    PRODUCTS: '/products',
    ABOUT: '/about',
    CONTACT: '/contact',
    CART: '/cart',
    CHECKOUT: '/checkout',
    BLOG: '/blog',
    RECIPES: '/recipes',
    FAQ: '/faq',
    SHIPPING: '/shipping',
    RETURNS: '/returns',
    PRIVACY: '/privacy-policy',
    TERMS: '/terms',
    REFUND_CANCELLATION: '/refund-cancellation-policy',
}